In [7]:
import numpy as np

In [8]:
my_list=[1,2,3,4]
arr=np.array(my_list)
print(arr)

[1 2 3 4]


In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape


(4,)

In [19]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[5,6,7,8,9]
arr=np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [5 6 7 8 9]]


In [31]:
# How indexing can be done in 2d
arr[2:3,:]
arr[1,1:4]

array([3, 4, 5])

In [37]:
arr=np.arange(0,10,2)
arr
arr=np.linspace(0,20,5)
arr

array([ 0.,  5., 10., 15., 20.])

In [43]:
# Copy function and broadcasting
arr[3:]=200
arr1=arr.copy()
arr
arr1[2:]=150
arr1

array([  0.,   5., 150., 150., 150.])

In [80]:
import pandas as pd
import numpy as np

data = np.arange(0, 20).reshape(5, 4)
index = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5']
columns = ['column1', 'column2', 'column3', 'column4']

df = pd.DataFrame(data, index=index, columns=columns)
df.head()
df.to_csv('Test1.csv')
df.loc['Row1']  
df.iloc[1:3,1:3].values
#df

array([[ 5,  6],
       [ 9, 10]])

In [82]:
# How to check the null condition
df.isnull().sum()
df.count()

column1    5
column2    5
column3    5
column4    5
dtype: int64